### ISSUE TITLE
Submit base parameters on all requests

### ISSUE THREAD

**Issue by uglymunky** [wyuenho/backgrid-filter#33]
I have a backgrid table that, by default, displays the results of a search.  I would like any new searches to append onto this search.  Also, when I clear a search, I'd like it to clear back to this default search.

For example, my table shows all users that have a status of "active".  If someone searches for "Sammy Davis", I want the search request to include the condition that the user's status is "active":  `q=active Sammy Davis`

I was thinking it would be useful to add a "baseParams" argument to the instantiation of a filter.

**Comment by wyuenho** [comment]
There's a `query` method in which you can easily override to prepend/append any value you'd like to the query parameter `q`. In your case, the fetched parameter can be stored on the collection instance itself, and retrieved when you construct the next query parameter.
