### ISSUE TITLE
Override search function

### ISSUE THREAD

**Issue by gigouni** [wyuenho/backgrid-filter#44]
Hi from France, 

I'm working on ServerSideFilter and I would like to override the search function. I tried to do this with the following lines :

<code>
var myfilter = new Backgrid.Extension.ServerSideFilter({

                tagName: "form",
                collection: mycollection,
                className: "backgrid-filter form-search",
                search: function (e) {
                    if (e) e.preventDefault();

                    var data = {};
                    var query = this.query();
                    if (query) data[this.name] = query;

                    if( data["search"].length > 2 ) {
                        console.log("Good");
                    }
                    else
                    {
                        console.log("Bad");
                    }

                    var collection = this.collection;

                    // go back to the first page on search
                    if (Backbone.PageableCollection &&
                        collection instanceof Backbone.PageableCollection) {
                        collection.getFirstPage({data: data, reset: true, fetch: true});
                    }
                    else collection.fetch({data: data, reset: true});

                },
                events: {
                    "keyup input[type=search]": "showClearButtonMaybe",
                    "click a[data-backgrid-action=clear]": "clear",
                    "submit": "search",
                    "click #backgrid_submit_button": "search"
                },
                name: "search",
                value: null,
                placeholder: "Recherche"

            });
</code>

I need to customize it to validate data (at least 3 letters). I used a HTML pattern but it doesn't work on Safari. When I try this code, It doesn't work neither. I don't pass through this custom search function. Do you know what could be the solution please ?

Thanks !

**Comment by krosenberg** [comment]
The ServerSideFilter is not set up to accept `search` as an option when creating an instance. Instead, you could extend the ServerSideFilter before instantiating it:
```
var CustomServerSideFilter = Backgrid.Extension.ServerSideFilter.extend({
    search: function(e) { /* your custom search method */ }
});

var myfilter = new CustomServerSideFilter({
    ... // the rest of your options except for 'search'
});
```
